version: "3"

services: 

  db:
    image: mysql:8.0.31
    container_name: eldorado_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:${MYSQL_PORT}
      
  app: 
    build: .
    container_name: eldorado_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports: 
    - 3333:${NODE_PORT}

# docker-compose up && docker-compose rm -fvs